# This workflow is set as a trusted publisher in pypi (publish.yaml)
name: Publish to PyPI

on:
  push:
    branches:
      - main

  workflow_dispatch:
    
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/supermeter-autowrapt
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # to fetch all tags too
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools
      - name: Build package
        run: python setup.py sdist
      - name: Set commit tag
        run: |
          VERSION=$(python setup.py --version)
          git tag "v$VERSION"
          git push origin "v$VERSION"
          echo tag="v$VERSION" >> $GITHUB_OUTPUT
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
